config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token

  root "reading_logs#index"

  resources :books
  resources :reading_logs

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reading_logs, dependent: :destroy

  validates :title,  presence: true
  validates :author, presence: true

  validate :published_at_cannot_be_feature

  def published_at_cannot_be_feature
    return unless published_at.present?

    if published_at > Date.today
      errors.add(:published_at, "未来の日付は使えません。")
    end
  end
end

app/models/book_log.rb
class BookLog < ApplicationRecord
  has_many :books, dependent: :destroy

  enum :status, {
    unread:   0,
    progress: 1,
    read:     2
  }, validate: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/reading_log.rb
class ReadingLog < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum :status, {
    unread:   0,
    progress: 1,
    read:     2
  }, validate: true

  accepts_nested_attributes_for :book
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  has_many :reading_logs, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_password_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      @user.sessions.destroy_all
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/reading_logs_controller.rb
class ReadingLogsController < ApplicationController
  def index
    @logs = ReadingLog.order(:created_at)
  end

  def show
    @log = ReadingLog.find(params[:id])
  end

  def new
    @log = Current.user.reading_logs.build
    @log.build_book
  end

  def create
    @log = Current.user.reading_logs.build(reading_log_params)

    if @log.save
      redirect_to @log, status: :see_other
    else
      render :new, status: :unprocessable_content
    end
  end

  def edit
    @log = ReadingLog.find(params[:id])
  end

  def update
    @log = ReadingLog.find(params[:id])

    if @log.update(reading_log_params)
      redirect_to @log, status: :see_other
    else
      render :edit, status: :unprocessable_content
    end

  end

  private

  def reading_log_params
    params.expect(reading_log: [
      :status,
      :comment,

      book_attributes: [
        :id,
        :title,
        :author,
        :publisher,
        :published_at,
        :_destroy
      ]
    ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookshelf" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Bookshelf">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reading_logs/_form.html.erb
<%= bootstrap_form_with model: log, url: [:reading_log] do |form| %>
  <%= bootstrap_fields_for :book, log.book do |book_form| %>
    <div>
      <%= book_form.text_field :title, required: true %>
    </div>
    <div>
      <%= book_form.text_field :author, required: true %>
    </div>
    <div>
      <%= book_form.text_field :publisher %>
    </div>
    <div>
      <%= book_form.date_field :published_at %>
    </div>
  <% end %>
  <div>
    <% ReadingLog.statuses.each_key do |status| %>
      <label>
        <%= form.radio_button :status,status, required: true %>
        <%= status %>
      </label>
    <% end %> 
  </div>
  <div>
    <%= form.text_area :comment %>
  </div>

  <button type="submit">保存</button>
<% end %>

app/views/reading_logs/edit.html.erb
<h1>Reading Log Edit</h1>
<%= render "form", log: @log %>

app/views/reading_logs/index.html.erb
<div class="mb-3">
  <h1>Reading Logs</h1>
  <table class="table table-borderless mb-5">
    <tbody>
      <% @logs.each do |log| %>
        <tr>
          <td><%= link_to log.book.title, reading_log_path(log), class: "link fs-3" %></td>
          <td class="date"><%= l(log.created_at.to_date) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reading_logs/new.html.erb
<h1>Reading Log New</h1>

<%= bootstrap_form_with model: @log, url: reading_logs_path do |form| %>
  <%= bootstrap_fields_for :book, @log.book do |book_form| %>
    <div>
      <%= book_form.text_field :title, required: true %>
    </div>
    <div>
      <%= book_form.text_field :author, required: true %>
    </div>
    <div>
      <%= book_form.text_field :publisher %>
    </div>
    <div>
      <%= book_form.date_field :published_at %>
    </div>
  <% end %>
  <div>
    <% ReadingLog.statuses.each_key do |status| %>
      <label>
        <%= form.radio_button :status,status, required: true %>
        <%= status %>
      </label>
    <% end %> 
  </div>
  <div>
    <%= form.text_area :comment %>
  </div>

  <button type="submit">保存</button>
<% end %>

app/views/reading_logs/show.html.erb
<div class="container">
  <h1>Reading Log</h1>
  <div class="main">
    <div class="book-title">
      <h2><%= @log.book.title %></h2>
    </div>
    <div class="status">
      <p><%= @log.status %></p>
    </div>
    <div class="comment">
      <p><%= @log.comment %></p>
    </div>
  </div>
</div>